language: c
sudo: false
before_install:
- sudo apt update
- sudo apt install -y gcc make autoconf automake autotools-dev libtool zlib1g-dev
script:
- cd ${TRAVIS_BUILD_DIR}
- aclocal
- autoreconf --install
- automake
- LDFLAGS='-static' ./configure
- make
- file gztool
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- mv gztool gztool-${TRAVIS_TAG#?}
- echo $(sha256sum gztool-${TRAVIS_TAG#?}) > sha256sums
- gzip gztool-${TRAVIS_TAG#?}
deploy:
  provider: releases
  api_key:
    secure: ZFfJ7RPla6QW7AVFXYWQE7ewA/35Xh/+b+1f/Jpc4yOQRoLMMaRNvtVA4b4S28PNpAlIkg8iFI0qMR5TNoW1bnUG0AfKSMcmsaf1DsZcEUJUezug9zSwJr2fu1Wsfs+1IL/kZs6rt11ps5ge1aK2Kg+eBkstonRzyEGup7sY2coUpedYzhDK2NLdFJpmv7yNPKYgTx6NgyTum+TmqQGkHL4A3r1QLbZsucnXnoxBhdu/7YIHG/TOir4YMpz9TEHWYn4d5FAzYB+jzbnwhtP0vS8RT729selhiZj1ln72MxTr+cX3G4y8o16RwklekkGO0yICKOGzgXtkJr25U9mJyMONTT0jWFmmLC+rXfTfOaQPkWnXz1ztQwA2Dwrz/o1HUskR2vxUvxk2EGuNs/9rJ7p4Wr9BT2dAhb9SB8HAXOcGSJfD9zOcewtv7ZK+1dryHQkZlbHEx2jM4OhRgO6DaLO3dUiyshXWlhGpWg+aX47+F1VBKfv3CdUo3VmkD6jaaUXmW8ZHcXCS+3lx6g14R3nFC0vWc7HTGtfq+EyZYELoZC44RyGJiLsD6H++5eFhygA0Yu5r/anMdRYU/KNqELQYdsMYi91vVpOq/GbloghzlR4fj9biA/udUhVgsc2iGevnlpmKOJNpVPOh67rUVUOOiJ3q8DD/j8Wx4OJs6CA=
  file:
    - gztool-${TRAVIS_TAG#?}.gz
    - sha256sums
  on:
    repo: criteo-forks/gztool
    tags: true
  skip_cleanup: 'true'
